Repository zlib-ng/zlib-ng, pull requests merged in 2019-01, with the labels that each got.

#286 bug #266: select std2 for gcc/clang ARM 32-bit builds
  match_p.h
Labels: optimization

#279 compile all files under arch/ with sanitizer flags
  Makefile.in
  configure
Labels: bug

#282 fix bug #225: account bits sent
  arch/x86/deflate_quick.c
Labels: bug

#283 fix bug #208: let the compiler generate code for unaligned stores
  arch/x86/deflate_quick.c
Labels: bug

#274 Update min cmake version
  CMakeLists.txt
  zlib.pc.cmakein
Labels: discussion, enhancement

#291 cleanup: remove partial do { } while constructs from macros
  arch/x86/crc_folding.c
Labels: cleanup

#292 cleanup: move code from arch/x86/crc_pclmulqdq.c to crc32.c
  CMakeLists.txt
  Makefile.in
  arch/x86/Makefile.in
  arch/x86/crc_pclmulqdq.c
  configure
  crc32.c
  win32/Makefile.msc
Labels: cleanup, enhancement
