Repository zlib-ng/zlib-ng, pull requests merged in 2019-03, with the labels that each got.

#293 ARM: remove configure flags --neon and --acle
  .travis.yml
  CMakeLists.txt
  configure
Labels: cleanup, enhancement

#297 ARM: check cpu feature once at init time
  arch/aarch64/arm.h
  arch/aarch64/armfeature.c
  arch/arm/Makefile.in
  arch/arm/arm.h
  arch/arm/armfeature.c
  arch/x86/x86.c
  arch/x86/x86.h
  deflate.c
  deflate_p.h
  functable.c
  inflate.c
  zutil.h
Labels: optimization

#299 win32: add missing makefile dependence
  win32/Makefile.arm
  win32/Makefile.msc
Labels: Needs testing

#302 Fixed arithmetic overflow warnings on Windows
  inffast.c
Labels: bug

#308 rename X86_SSE2_FILL_WINDOW to X86_SSE2
  CMakeLists.txt
  arch/x86/fill_window_sse.c
  configure
  functable.c
  win32/Makefile.msc
Labels: cleanup

#319 unify uses of __ARM_FEATURE_CRC32
  functable.c
Labels: cleanup

#323 Change force-sse2 behavior.
  CMakeLists.txt
  configure
  functable.c
Labels: cleanup, optimization

#324 Update x86 and x86_64 arch checks
  arch/x86/deflate_quick.c
  deflate.c
  deflate.h
Labels: cleanup, enhancement

#317 factor out code in arch/{arm,aarch64}
  CMakeLists.txt
  Makefile.in
  arch/aarch64/Makefile.in
  arch/aarch64/adler32_neon.c
  arch/aarch64/adler32_neon.h
  arch/aarch64/arm.h
  arch/aarch64/armfeature.c
  arch/aarch64/crc32_acle.c
  arch/aarch64/fill_window_arm.c
  arch/aarch64/insert_string_acle.c
  arch/arm/armfeature.c
  arch/arm/crc32_acle.c
  configure
  zutil.h
Labels: cleanup

#311 fix all ASan errors on aarch64
  arch/arm/insert_string_acle.c
  match_p.h
Labels: bug

#300 update makefile dependences
  Makefile.in
  arch/arm/Makefile.in
  arch/x86/Makefile.in
  configure
Labels: cleanup, enhancement

#322 use sizeof(type) instead of magic numbers
  arch/arm/crc32_acle.c
Labels: cleanup
