Repository zlib-ng/zlib-ng, pull requests merged in 2020-09, with the labels that each got.

#743 Rename variable to correctly indicate register usage
  arch/x86/slide_avx.c
Labels: cleanup

#744 Remove FORCE_STATIC and FORCE_STORED
  trees.c
Labels: cleanup

#664 Added AVX support to chunkset functions.
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/chunkset_avx.c
  chunkset_tpl.h
  configure
  functable.c
  win32/Makefile.msc
Labels: Architecture, Benchmarks wanted, enhancement, optimization

#746 Add support for ZLIB_COMPÅT in nmake Makefiles for ARM/AArch64.
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: Build Env

#750 Remove some of the references to the unreleased zlib 1.2.12
  deflate.c
  inftrees.c
  zutil.c
Labels: cleanup

#747 Allow forcing UNALIGNED[64]_OK off in cmake.
  .github/workflows/cmake.yml
  CMakeLists.txt
  README.md
Labels: Build Env, enhancement

#755 Fixed buf resource leak in gz_compress when USE_MMAP is defined.
  test/minigzip.c
Labels: bug

#754 Added ubuntu mingw cross-compile CI instances to cmake GHA.
  .github/workflows/cmake.yml
  cmake/toolchain-mingw-i686.cmake
  cmake/toolchain-mingw-x86_64.cmake
Labels: Continuous Integration

#756 Optionally include gzguts.h with WITH_GZFILEOP flag.
  CMakeLists.txt
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
  zutil.c
Labels: cleanup

#757 Move gzclose() to gzlib.c.
  CMakeLists.txt
  INDEX.md
  Makefile.in
  gzclose.c
  gzlib.c
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: cleanup

#758 Fixed match_byte casting warning in compare256_unaligned_64_static.
  compare258.c
Labels: cleanup

#760 Add missing z_const to fuzzers.
  test/fuzz/example_dict_fuzzer.c
  test/fuzz/example_flush_fuzzer.c
  test/fuzz/example_small_fuzzer.c
Labels: cleanup

#759 Need 3 chunks for chunkmemset_3 and chunkmemset_6.
  CMakeLists.txt
  arch/arm/chunkset_neon.c
  chunkset_tpl.h
  test/GH-751/test.txt
  test/Makefile.in
Labels: Compatibility, bug

#762 Remove gcov-7 install since warnings on gcov-8 no longer occur
  .github/workflows/cmake.yml
Labels: Continuous Integration

#764 Remove unused F_OPEN preprocessor macro.
  zutil.h
Labels: cleanup

#767 Remove NIL preprocessor macro which isn't consistently enforced.
  deflate.c
  deflate.h
  deflate_slow.c
Labels: cleanup

#769 Fixed tab indentation for inffixed_tbl.h.
  inffixed_tbl.h
  tools/makefixed.c
Labels: cleanup

#771 Fix unsigned integer overflow ASAN error for align_diff in crc_folding
  arch/x86/crc_folding.c
Labels: bug
