Repository zlib-ng/zlib-ng, pull requests merged in 2020-08, with the labels that each got.

#701 Fix signature of adler32(), adler32_combine(), adler32_combine64() and adler32_z() in compat mode.
  adler32.c
  zlib.h
Labels: API

#696 Remove forward declarations for stub functions
  functable.c
Labels: cleanup

#682 Fixed extra symbols added to ABI when zlib-compat specified.
  adler32.c
  arch/power/power.c
  arch/x86/adler32_avx.c
  arch/x86/adler32_ssse3.c
  arch/x86/compare258_avx.c
  arch/x86/compare258_sse.c
  chunkset_tpl.h
  compare258.c
  deflate.c
  inftrees.c
  match_tpl.h
  zlib.map
  zutil.c
  zutil.h
Labels: Build Env, cleanup

#693 Remove ARM crc instruction set from NEONFLAG.
  CMakeLists.txt
Labels: Build Env, cleanup

#702 Fix signature of crc32_combine(), crc32_combine64() and crc32_z() in compat mode.
  crc32.c
  zlib.h
Labels: API

#712 Fix unaligned double word accesses in chunkset_neon on ARMv7
  arch/arm/chunkset_neon.c
Labels: Architecture

#715 Optimize inflate_fast for a 0.8% speedup
  inffast.c
Labels: optimization

#718 Remove NO_DIVIDE from adler32.
  adler32.c
  adler32_p.h
  arch/x86/adler32_avx.c
  arch/x86/adler32_ssse3.c
Labels: cleanup

#710 Honor CFLAGS when linking
  Makefile.in
Labels: Build Env

#719 Harmonize the CPU architecture preprocessor definitions.
  CMakeLists.txt
  configure
  deflate.c
  fallback_builtins.h
  functable.c
  inflate.c
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
  zutil.h
Labels: cleanup

#732 Fix unquoted variables in cmake if statements
  CMakeLists.txt
Labels: Build Env

#725 Simplify and optimize insert_string template
  functable.c
  functable.h
  insert_string_tpl.h
Labels: cleanup, optimization

#691 Use mainline codecov repository
  .github/workflows/cmake.yml
Labels: Build Env, cleanup
