Repository zlib-ng/zlib-ng, pull requests merged in 2020-05, with the labels that each got.

#579 Use 64-bit bit buffer when emitting codes.
  arch/x86/deflate_quick.c
  deflate.c
  deflate.h
  trees.c
  trees_emit.h
Labels: optimization

#572 Simplify generic hash function using knuth's multiplicative hash
  deflate.c
  deflate.h
  deflate_fast.c
  deflate_medium.c
  insert_string.c
Labels: optimization

#587 Fixed compiler warning about inline already being defined
  zutil.h
Labels: enhancement

#580 Remove support for DYNAMIC_CRC_TABLE
  functable.c
  zutil.c
Labels: cleanup

#586 Added features list to README.md.
  README.md
Labels: enhancement

#584 Set binary mode for stdin and stdout in switchlevels.
  test/switchlevels.c
Labels: bug

#583 Check distance in deflate_quick using MAX_DIST(s)
  arch/x86/deflate_quick.c
Labels: bug, discussion

#585 Fixed zero length stored block left open when using Z_SYNC_FLUSH.
  CMakeLists.txt
  arch/x86/deflate_quick.c
  trees.c
  trees_emit.h
Labels: bug

#598 Fixed missing window_padding added to window alloc size in deflateCopy
  deflate.c
Labels: bug

#613 Cache chocolatey packages on Windows for CMake workflow.
  .github/workflows/cmake.yml
Labels: Continuous Integration, enhancement

#604 Use a constant to load adler-32 initial hash value.
  deflate.c
  inflate.c
  zutil.h
Labels: cleanup, optimization

#608 Added ability to set window bits for switchlevels.
  test/switchlevels.c
Labels: enhancement

#600 Remove IPos typedef.
  arch/x86/deflate_quick.c
  deflate.c
  deflate.h
  deflate_fast.c
  deflate_medium.c
  deflate_p.h
  deflate_slow.c
  functable.c
  functable.h
  match_tpl.h
Labels: cleanup

#597 Remove toofar checks
  deflate_medium.c
  deflate_slow.c
Labels: discussion, optimization
