Repository zlib-ng/zlib-ng, pull requests merged in 2020-11, with the labels that each got.

#801 Remove unnecessary name array from matrix.
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
  .github/workflows/nmake.yml
  .github/workflows/pkgcheck.yml
  .github/workflows/release.yml
Labels: Continuous Integration

#798 Fixed minigzip_fuzzer not compiling on latest macOS
  test/fuzz/minigzip_fuzzer.c
Labels: Build Env, Continuous Integration

#797 Fixed format specifier warning in build_tree call to Tracev.
  trees.c
Labels: cleanup

#799 Fixed ubsan warning in gzfread due to size_t overflow.
  gzread.c
Labels: bug

#796 Fixed ubsan error when building tree with no symbols.
  trees.c
Labels: bug

#802 Add CI run that tests UNALIGNED_OK without UNALIGNED64_OK.
  .github/workflows/cmake.yml
Labels: Continuous Integration
