Repository zlib-ng/zlib-ng, pull requests merged in 2020-02, with the labels that each got.

#507 Fix double specification of -O2 in ./configure
  configure
Labels: bug

#493 Removed MAX_DIST2 which is incompatible with INFLATE_STRICT.
  deflate_medium.c
Labels: Benchmarks wanted, bug

#501 Fixed wrong compiler names specified in build matrix
  .github/workflows/configure.yml
Labels: Rebase needed, cleanup

#510 Use value already stored in wsize
  arch/x86/slide_sse.c
Labels: cleanup, optimization

#504 Improvements to pending buffer functions
  deflate.c
  deflate.h
  trees.c
Labels: Rebase needed, enhancement

#512 Fixed compiler warning when using BITS macro.
  inflate_p.h
Labels: cleanup

#506 Support aligned alloc/free functions for Windows
  zutil.c
Labels: cleanup, enhancement

#495 Enable CI options explicitly so forked repositories don't fail CI.
  .github/workflows/cmake.yml
  CMakeLists.txt
  README.md
Labels: bug, cleanup

#502 Add initial AVX2 support.
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/fill_window_sse.c
  arch/x86/slide_avx.c
  arch/x86/x86.c
  arch/x86/x86.h
  configure
  win32/Makefile.msc
Labels: Benchmarks wanted, optimization
