Repository zlib-ng/zlib-ng, pull requests merged in 2020-06, with the labels that each got.

#616 Fixed multi-line assembly macro in UPDATE_HASH for MSVC
  arch/x86/insert_string_sse.c
Labels: bug

#622 Use char* instead of caddr_t
  test/minigzip.c
Labels: Build Env

#614 Run compression level tests without open mode.
  CMakeLists.txt
Labels: Continuous Integration

#596 Add a workflow for clang and gcc static analysis
  .github/workflows/analyze.yml
Labels: Continuous Integration, enhancement

#590 Make deflate_quick algorithm available to all platforms.
  CMakeLists.txt
  Makefile.in
  arch/x86/Makefile.in
  compress.c
  configure
  deflate.c
  deflate_quick.c
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: cleanup, enhancement

#610 Fix specification of warnings for intel compilers
  CMakeLists.txt
Labels: enhancement

#566 Clean up windows defines, use _WIN32
  gzguts.h
  gzlib.c
  test/fuzz/minigzip_fuzzer.c
  test/minigzip.c
  zconf-ng.h.in
  zconf.h.in
  zendian.h
  zlib-ng.h
  zlib.h
  zutil.h
Labels: cleanup

#629 Fixed deflate_quick algorithm not being used due to old check.
  deflate.c
Labels: bug

#628 Fixed defined WIN32 in switchlevels should be _WIN32.
  test/switchlevels.c
Labels: Continuous Integration, bug

#625 Disable unaligned access of > 4 bytes on 32-bit arm
  CMakeLists.txt
  compare258.c
  configure
  functable.c
  win32/Makefile.a64
  win32/Makefile.msc
Labels: Architecture, Build Env, bug

#589 Use standard int types in zlib-ng api
  deflate.c
  infback.c
  inflate.c
  test/example.c
  zlib-ng.h
Labels: API, enhancement

#634 Remove Borland C++ compiler references
  gzlib.c
  zconf-ng.h.in
  zconf.h.in
Labels: cleanup

#473 Added regression test for deflateEnd returning -3 when using deflate quick.
  CMakeLists.txt
  test/GH-382/defneg3.dat
  test/README.md
  test/minideflate.c
Labels: enhancement

#640 Remove unnecessary adler32_neon.h.
  CMakeLists.txt
  arch/arm/adler32_neon.c
  arch/arm/adler32_neon.h
Labels: cleanup

#641 Updated features with new Adler32 implementations.
  README.md
Labels: cleanup

#620 Fixed deflate_quick block emitting
  deflate_quick.c
Labels: bug

#644 deflate_slow: ignore unused return value from final call to zng_tr_tally_lit
  deflate_slow.c
Labels: cleanup

#649 Do not use word xor (iso646 legacy)
  compare258.c
Labels: cleanup

#650 Add cmake build dir to gitignore
  .gitignore
Labels: Build Env, cleanup

#652 Fixed casting warnings
  deflate.c
  gzlib.c
Labels: cleanup

#632 Determine whether platform supports dll declspec
  zconf-ng.h.in
  zconf.h.in
Labels: Build Env

#645 Separate defines on individual lines to prevent merge conflicts.
  CMakeLists.txt
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: cleanup

#657 Fixes to deflate_quick algorithm when compiling with USE_MMAP
  deflate_quick.c
Labels: bug

#651 Added ZLIB_REGISTER to disable register keyword for C++.
  arch/arm/crc32_acle.c
  arch/arm/slide_neon.c
  arch/s390/dfltcc_common.c
  arch/s390/dfltcc_detail.h
  crc32.c
  match_tpl.h
  trees.c
  zutil.h
Labels: cleanup

#662 Fixed wrong size being used in calloc in test_deflate_set_header.
  test/example.c
Labels: cleanup

#663 Use local match_len variable in deflate_slow.
  deflate.c
  deflate_slow.c
Labels: optimization
