Repository zlib-ng/zlib-ng, pull requests merged in 2020-07, with the labels that each got.

#665 Fixed unsigned integer overflow in adler32_avx and adler32_ssse3 when len is zero.
  arch/x86/adler32_avx.c
  arch/x86/adler32_ssse3.c
Labels: enhancement

#669 Apply -mfpu=neon flag only to files using neon instructions with configure.
  arch/arm/Makefile.in
  configure
Labels: Build Env

#667 Remove some extra ci configurations.
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
Labels: Continuous Integration

#660 Modify cmake to apply native flag when using intrinsic flags
  CMakeLists.txt
Labels: Build Env, bug, cleanup

#668 Fixed issues with float abi in cmake
  CMakeLists.txt
Labels: Build Env

#673 Added powerpc instances to CI for configure.
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
  configure
Labels: Continuous Integration, enhancement

#672 Remove duplicate Windows GCC CI cmake instance.
  .github/workflows/cmake.yml
Labels: Continuous Integration, cleanup

#670 Add/improve likely/unlikely hinting to all deflate algorithms.
  deflate_fast.c
  deflate_medium.c
  deflate_quick.c
  deflate_slow.c
Labels: optimization

#676 configure: fix typo (.o in shared library)
  configure
Labels: Build Env

#648 Add GitHub Actions workflow for creating releases.
  .github/workflows/release.yml
  CMakeLists.txt
  README.md
Labels: Continuous Integration, enhancement

#683 Remove current directory library include path in configure not in cmake
  configure
Labels: Build Env

#684 Fix long string warning on adler32_test
  test/adler32_test.c
Labels: cleanup

#685 Fixed chunksize not being initialized when using inflateBack.
  infback.c
Labels: bug

#687 Added SSE4.2 inline assembly check for configure script.
  configure
Labels: Build Env

#688 Added missing switch for configure script --native to readme.
  README.md
  configure
Labels: cleanup

#674 Default to optimization level 2 in cmake for release mode.
  CMakeLists.txt
Labels: Build Env

#692 Make static libraries produced by cmake and configure identical.
  .github/workflows/pkgcheck.yml
  .gitignore
  CMakeLists.txt
  Makefile.in
  test/pkgcheck.sh
Labels: Build Env

#686 Return proper exit code after flushing end block in deflate_quick.
  deflate_quick.c
Labels: bug
