Repository zlib-ng/zlib-ng, pull requests merged in 2020-10, with the labels that each got.

#774 Add 'diffoscope' for MacOS in pkgcheck.yml
  .github/workflows/pkgcheck.yml
Labels: Continuous Integration

#779 Fix constness in DFLTCC code
  arch/s390/dfltcc_detail.h
Labels: cleanup

#780 Fixed dereference of possibly null head variable in test_deflate_set_header
  test/example.c
Labels: cleanup

#786 Abort CI tests on sanitizer error.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#788 Avoid shifts of negative values inflateMark()
  inflate.c
Labels: bug

#789 Fixed left shift ubsan warning in PULLBYTE.
  infback.c
Labels: bug

#778 Fix incorrect inflateSyncPoint() return value with DFLTCC
  arch/s390/README.md
  arch/s390/dfltcc_inflate.h
  inflate.c
Labels: Architecture

#781 Elevate warnings to errors to trigger failure on static analyzer
  .github/workflows/analyze.yml
Labels: Continuous Integration

#772 Fixed unsigned integer overflow ASAN error when hash_head > s->strstart.
  deflate_fast.c
  deflate_medium.c
  deflate_quick.c
  deflate_slow.c
Labels: bug

#768 Combine option and add_feature_info in CMake.
  CMakeLists.txt
Labels: cleanup
