Repository zlib-ng/zlib-ng, pull requests merged in 2021-05, with the labels that each got.

#939 Decompress gzip compressed archive to a separate file to prevent corruption issues on macOS.
  cmake/test-compress.cmake
Labels: Continuous Integration

#944 Reintroduce Z_SOLO support for compatibility mode.
  zlib.h
Labels: Compatibility

#942 Fix cmake detection of risc-v (32 and 64 bit)
  cmake/detect-arch.c
  cmake/detect-arch.cmake
Labels: Architecture, Build Env

#949 upgrade links to HTTPS
  FAQ.zlib
  arch/s390/README.md
  arch/x86/crc_folding.c
  deflate.c
  doc/algorithm.txt
  doc/rfc1952.txt
  test/CVE-2003-0107.c
  test/README.md
  win32/DLL_FAQ.txt
  win32/README-WIN32.txt
  win32/zlib-ng1.rc
  win32/zlib1.rc
  zlib-ng.h
  zlib.h
Labels: cleanup

#951 Version 2.0.3
  Makefile.in
  zlib-ng.h
  zlib.h
  zutil.c
Labels: Needs testing

#961 Spelling fixes
  .github/workflows/cmake.yml
  CMakeLists.txt
  FAQ.zlib
  PORTING.md
  cmake/run-and-compare.cmake
  cmake/run-and-redirect.cmake
  deflate.c
  inftrees.h
  test/abicheck.md
  test/data/lcet10.txt
  zlib-ng.h
  zlib.h
Labels: cleanup

#959 Fix compiler detection to avoid bad mpicc match
  CMakeLists.txt
Labels: Build Env

#964 Fix build on NetBSD
  zutil_p.h
Labels: Build Env

#976 Remove unnecessary test for stdarg.h
  CMakeLists.txt
Labels: cleanup

#981 Use latest version of llvm-cov to prevent code coverage version mismatch
  .github/workflows/cmake.yml
Labels: Continuous Integration
