Repository zlib-ng/zlib-ng, pull requests merged in 2021-12, with the labels that each got.

#1060 Fixed minideflate write buffers being overwritten.
  test/minideflate.c
Labels: bug

#1061 Reuse adler32_len_64 in adler32_c.
  adler32.c
  adler32_p.h
Labels: cleanup

#1053 AVX2 optimizations
  arch/x86/adler32_avx.c
Labels: optimization, Architecture

#1063 Workaround for installation failure of wine32.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1070 inttypes.h includes stdint.h, so only include one of them.
  arch/x86/crc32_fold_pclmulqdq.c
  crc32.c
  crc32_comb.c
  test/example.c
  test/fuzz/checksum_fuzzer.c
  test/fuzz/compress_fuzzer.c
  test/fuzz/example_dict_fuzzer.c
  test/fuzz/example_flush_fuzzer.c
  test/fuzz/example_large_fuzzer.c
  test/fuzz/example_small_fuzzer.c
  test/infcover.c
  test/minideflate.c
  trees_emit.h
Labels: cleanup

#1069 Remove gz_intmax
  gzguts.h
  gzlib.c
  zlib-ng.map
  zlib.map
  zlib_name_mangling-ng.h.in
  zlib_name_mangling.h.in
Labels: cleanup

#1075 Avoid warning C4295 when using Visual C++ and maintainer warnings are enabled.
  test/deflate_quick_bi_valid.c
Labels: cleanup

#1071 Fix deflateBound and compressBound returning very small size estimates.
  compress.c
  deflate.c
  test/switchlevels.c
  zutil.h
Labels: bug

#1079 Upgrade version of GitHub checkout actions.
  .github/workflows/libpng.yml
  .github/workflows/nmake.yml
  .github/workflows/pkgcheck.yml
  .github/workflows/release.yml
Labels: Continuous Integration

#1080 Fixed crc32_combine_gen declaration warning in zlib-ng API.
  crc32_comb.c
Labels: API
