Repository zlib-ng/zlib-ng, pull requests merged in 2021-06, with the labels that each got.

#983 Use SET_BAD macro in inflateBack.
  infback.c
Labels: cleanup

#984 Move MIN() macro to zbuild.h
  deflate_p.h
  zbuild.h
Labels: cleanup

#991 Open up develop branch for non-stable commits.
  Makefile.in
  test/example.c
  zlib-ng.h
  zlib.h
  zutil.c
Labels: Next Devel

#863 CodeFactor fixes for configure script
  configure
Labels: Next Devel, cleanup

#904 Remove extra check that always is false in compare256_c_static.
  compare258.c
Labels: Next Devel, cleanup

#868 Increase size of gzip output buffer
  CMakeLists.txt
  gzguts.h
Labels: Next Devel, optimization

#948 Change bi_reverse to use a much faster bit manipulation implementation.
  deflate.h
  tools/maketrees.c
  trees.c
Labels: Next Devel, optimization

#988 Use MIN and MAX macros.
  deflate.c
  deflate_stored.c
  infback.c
  inflate.c
  inftrees.c
  zbuild.h
Labels: Next Devel, cleanup

#996 Improve sanitizer selection and add support for selecting Thread sanitizer
  CMakeLists.txt
  cmake/detect-sanitizer.cmake
Labels: Build Env, enhancement

#997 Added Z_UNUSED define for ignore unused variables.
  deflate.h
  inflate.c
  test/example.c
  test/fuzz/checksum_fuzzer.c
  test/fuzz/standalone_fuzz_target_runner.c
  test/infcover.c
  trees_emit.h
  zbuild.h
  zutil.c
Labels: cleanup

#998 Fixed indentation in CMakeLists.txt.
  CMakeLists.txt
Labels: cleanup

#1000 Reduce number of branches in partial chunk copy when no optimizations.
  arch/arm/chunkset_neon.c
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse.c
  chunkset.c
  chunkset_tpl.h
Labels: optimization

#999 Show unavailable features in CMake feature summary.
  CMakeLists.txt
Labels: Build Env, enhancement

#1006 Minor optimization of inftrees.c based on profiling
  inftrees.c
Labels: optimization

#1014 Version 2.0.5
  Makefile.in
  zlib-ng.h
  zlib.h
  zutil.c
Labels: Needs testing

#890 Added low memory configuration option to CMake and configure.
  CMakeLists.txt
  configure
Labels: Next Devel, enhancement

#1009 [Power8] Add chunk*_power8.
  CMakeLists.txt
  README.md
  arch/power/Makefile.in
  arch/power/chunkset_power8.c
  configure
  functable.c
Labels: Architecture, optimization

#1020 Fixed missing enclosing parentheses for ZSWAP64
  zutil.h
Labels: bug

#1010 Remove deflate_state dependency from crc_folding.
  arch/x86/crc_folding.c
  arch/x86/crc_folding.h
  crc32.c
Labels: cleanup

#1011 Remove extra division operation in chunkcopy
  chunkset_tpl.h
Labels: cleanup
