Repository zlib-ng/zlib-ng, pull requests merged in 2021-03, with the labels that each got.

#865 Remove misleading manpage and update README.md.
  CMakeLists.txt
  INDEX.md
  Makefile.in
  README.md
  zlib.3
Labels: cleanup

#866 Stable release 2.0.0
  Makefile.in
  zlib-ng.h
  zlib.h
  zutil.c
Labels: Needs testing

#885 Cmake: Accept custom install dirs in various formats from command line.
  CMakeLists.txt
  cmake/detect-install-dirs.cmake
Labels: Build Env

#893 Reduce the time it takes for MinGW jobs.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#892 Add a CMake macro for simple test executables
  CMakeLists.txt
Labels: cleanup

#897 Restore hash_head != 0 checks
  CMakeLists.txt
  deflate_fast.c
  deflate_medium.c
  deflate_slow.c
  test/hash_head_0.c
Labels: bug

#898 Only perform auto-detection of floating point ABI on ARM arch.
  CMakeLists.txt
Labels: Build Env

#899 Support for posix_memalign in FreeBSD 11.
  zutil_p.h
Labels: Build Env

#900 Detect unsupported VS at configure time (and not at compile time)
  CMakeLists.txt
Labels: Build Env

#917 Include porting guide in GH release packages.
  .github/workflows/release.yml
Labels: Continuous Integration
