Repository zlib-ng/zlib-ng, pull requests merged in 2021-04, with the labels that each got.

#915 Alias ZEXTERN, ZEXPORT and ZEXPORTVA to Z_EXTERN, Z_EXPORT and Z_EXPORTVA respectively.
  zconf.h.in
Labels: Compatibility

#916 Added Windows ARM and ARM64 binaries in releases.
  .github/workflows/release.yml
Labels: Continuous Integration

#918 Check support for ARM float-abi compiler flag auto-detected value.
  CMakeLists.txt
  configure
Labels: Architecture, Build Env

#922 Write generated files during tests to CMake's build directory.
  CMakeLists.txt
  cmake/detect-arch.cmake
  cmake/test-compress.cmake
Labels: Build Env

#921 Remove unnecessary malloc.h header include
  test/fuzz/minigzip_fuzzer.c
  test/minigzip.c
Labels: Next Devel, cleanup
