Repository zlib-ng/zlib-ng, pull requests merged in 2022-12, with the labels that each got.

#1376 Ubuntu 22.04 CI image doesn't have clang-11 installed.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1375 Update wine32 dependencies for Ubuntu 22.04
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1371 Fixed cast to smaller integer type on MSYS2 Clang64.
  crc32_braid.c
Labels: Build Env, Warnings fix

#1372 IBM zSystems DFLTCC: Support inflate with small window
  arch/s390/README.md
  arch/s390/dfltcc_common.c
  arch/s390/dfltcc_common.h
  arch/s390/dfltcc_deflate.c
  arch/s390/dfltcc_detail.h
  arch/s390/dfltcc_inflate.c
  arch/s390/dfltcc_inflate.h
  inflate.c
  inflate_p.h
  test/CMakeLists.txt
  test/test_small_window.cc
Labels: Architecture

#1381 llvm-cov-11 needs llvm-11 on Ubuntu 22.04.
  .github/workflows/cmake.yml
  .github/workflows/pigz.yml
Labels: Continuous Integration

#1387 Tell scan-build ASSERT_TRUE() behaves like assert().
  test/test_aligned_alloc.cc
  test/test_compare256.cc
  test/test_compress_bound.cc
  test/test_deflate_bound.cc
  test/test_deflate_dict.cc
  test/test_deflate_header.cc
  test/test_deflate_params.cc
  test/test_deflate_pending.cc
  test/test_gzio.cc
  test/test_large_buffers.cc
  test/test_shared.h
Labels: Continuous Integration, Build Env

#1395 Fixed Ubuntu 22 Clang MSAN CI instance.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1394 Use Ubuntu 20.04 images for SPARC64 and PPC64LE tests
  .github/workflows/cmake.yml
Labels: Continuous Integration
