Repository zlib-ng/zlib-ng, pull requests merged in 2022-08, with the labels that each got.

#1316 Treat arm64 as aarch64 for Apple M1.
  cmake/detect-arch.c
  configure
Labels: Build Env

#1309 Don't use unaligned access for memcpy instructions
  arch/arm/chunkset_neon.c
  arch/power/chunkset_power8.c
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse2.c
  arch/x86/chunkset_sse41.c
  chunkset.c
  compare256.c
  deflate.h
  inffast.c
  inflate_p.h
  insert_string_tpl.h
  match_tpl.h
  zbuild.h
Labels: bug

#1311 Fix inflateBack to detect invalid input with distances too far.
  infback.c
Labels: bug

#1314 Reorganize cmake scripts for tests.
  CMakeLists.txt
  test/CMakeLists.txt
  test/cmake/compress-and-verify.cmake
  test/cmake/run-and-compare.cmake
  test/cmake/run-and-redirect.cmake
  test/cmake/test-cves.cmake
  test/cmake/test-data.cmake
  test/cmake/test-issues.cmake
  test/cmake/test-tools.cmake
  test/pigz/CMakeLists.txt
Labels: cleanup, Testing Framework

#1318 cmake: respect custom `RC` flags and delete `GCC_WINDRES`
  CMakeLists.txt
  configure
  win32/zlib-ng1.rc
  win32/zlib1.rc
Labels: cleanup, Build Env
