Repository zlib-ng/zlib-ng, pull requests merged in 2022-06, with the labels that each got.

#1277 Proposal: Allow external gtest
  test/CMakeLists.txt
Labels: Build Env

#1252 Create crc32 fold templates
  arch/x86/crc32_fold_pclmulqdq.c
  arch/x86/crc32_fold_pclmulqdq_tpl.h
  arch/x86/crc32_fold_vpclmulqdq.c
  arch/x86/crc32_fold_vpclmulqdq_tpl.h
  cpu_features.h
  crc32_fold.h
  functable.c
Labels: cleanup, Architecture

#1284 Fixed signed warnings in GZ unit tests.
  test/test_gzio.cc
Labels: Warnings fix

#1285 Remove unused chunkcopy_safe function prototypes.
  arch/arm/chunkset_neon.c
  arch/power/chunkset_power8.c
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse2.c
  chunkset.c
  cpu_features.h
Labels: cleanup

#1289 zlib 1.2.12
  README.md
  crc32_braid.c
  crc32_braid_comb.c
  deflate.c
  gzguts.h
  gzlib.c
  gzread.c.in
  gzwrite.c
  infback.c
  inflate.c
  inflate.h
  inftrees.c
  inftrees.h
  tools/makecrct.c
  trees.c
  zlib.h.in
  zutil.h
Labels: Compatibility

#1286 Fixed inflate size conversion warning in chunkcopy_safe.
  inflate_p.h
Labels: Warnings fix

#1288 Fixed conversion warnings for wsize in slide_hash_c.
  slide_hash.c
Labels: Warnings fix

#1293 Handle invalid windowBits in init functions
  deflate.c
  inflate.c
Labels: Sanitizer issue

#1292 Add public compile definition for zlib-ng API
  CMakeLists.txt
Labels: Build Env

#1297 In compatibility mode, always define z_crc_t as uint32_t for backwards compatibility.
  configure
  zconf-ng.h.in
  zconf.h.in
  zlib-ng.h.in
  zlib.h.in
Labels: Compatibility

#1290 Add a test for concurrently modifying deflate() input
  test/CMakeLists.txt
  test/test_deflate_concurrency.cc
Labels: Testing Framework

#1282 Improve the swizzle of the memory magazine fed in a chunk copy for neon
  arch/arm/chunkset_neon.c
  arch/generic/chunk_permute_table.h
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse41.c
Labels: optimization

#1308 Bump _POSIX_C_SOURCE to 200809 for strdup()
  test/minideflate.c
  zbuild.h
Labels: Build Env, Warnings fix

#1274 fix off-by-one bug in crc32_acle.c
  arch/arm/crc32_acle.c
Labels: discussion
