Repository zlib-ng/zlib-ng, pull requests merged in 2022-05, with the labels that each got.

#1258 Regression: stream adler checksum no longer matches after inflateSetDictionary (bisected)
  test/test_dict.cc
Labels: Testing Framework

#1261 Fixed MSVC warning about unknown option for AVX512 flag.
  cmake/detect-intrinsics.cmake
Labels: Warnings fix

#1266 Remove unused chunkmemset_1 code.
  arch/arm/chunkset_neon.c
  arch/power/chunkset_power8.c
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse2.c
  chunkset.c
Labels: cleanup

#1265 Fixed warning about strict prototypes for cpu_check_features.
  cpu_features.h
Labels: Warnings fix

#1254 NEON version of compare256
  CMakeLists.txt
  README.md
  arch/arm/Makefile.in
  arch/arm/compare256_neon.c
  configure
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_compare256.cc
  test/test_compare256.cc
  win32/Makefile.a64
  win32/Makefile.arm
Labels: optimization, Architecture

#1255 Implement power9 version of compare256.
  CMakeLists.txt
  README.md
  arch/power/Makefile.in
  arch/power/compare256_power9.c
  arch/power/power_features.c
  arch/power/power_features.h
  cmake/detect-intrinsics.cmake
  configure
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_compare256.cc
  test/test_compare256.cc
Labels: optimization, Architecture

#1271 Fixed issue #1264: Use fallback for _mm256_zextsi128_si256 on Xcode <…
  fallback_builtins.h
Labels: Build Env

#1272 Fixed incorrect case for __clang__ preprocessor macro in zbuild.h.
  zbuild.h
Labels: Build Env

#1273 Make directory for output files
  cmake/run-and-compare.cmake
Labels: Build Env

#1245 Improved chunkset substantially where it's heavily used
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/chunk_permute_table.h
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_sse41.c
  chunkset_tpl.h
  configure
  cpu_features.h
  functable.c
  inflate_p.h
Labels: optimization, Rebase needed, Architecture
