Repository zlib-ng/zlib-ng, pull requests merged in 2022-04, with the labels that each got.

#1218 Remove support for building fuzzers from configure.
  Makefile.in
  README.md
  configure
  test/Makefile.in
Labels: cleanup, Build Env

#1221 Grammar fixes
  PORTING.md
  README.md
Labels: cleanup

#1222 abicheck.sh: implement --refresh-if option as documented.
  .github/workflows/pkgcheck.yml
  test/abicheck.md
  test/abicheck.sh
Labels: Compatibility

#1224 Use latest stable version of google test
  test/CMakeLists.txt
Labels: Build Env

#1225 Move fuzzer cmake into fuzz directory.
  CMakeLists.txt
  test/fuzz/CMakeLists.txt
Labels: cleanup

#1226 Fixed building tests when -DWITH_GZFILEOP=OFF
  test/CMakeLists.txt
Labels: Testing Framework

#1227 abicheck.sh: zlib-ng configure is a bash script, not a sh script
  test/abicheck.sh
Labels: Compatibility

#1229 Fixed missing crc32_combine exports for zlib 1.2.12.
  win32/zlib.def.in
  win32/zlibcompat.def.in
  zlib_name_mangling-ng.h.in
  zlib_name_mangling.h.in
Labels: Compatibility

#1230 abicheck.sh: don't export CHOST if it wasn't already exported.
  test/abicheck.sh
Labels: Compatibility

#1223 Remove sanitizer support from configure.
  .github/workflows/configure.yml
  README.md
  configure
Labels: cleanup, Build Env

#1237 Fix the custom PNG image based benchmark
  test/benchmarks/benchmark_png_shared.h
Labels: bug, Testing Framework

#1238 Mimic minigzip behavior and only unlink files if not using -c.
  test/minideflate.c
Labels: bug, Testing Framework

#1242 Fixed off-by-one error when benchmarking compare256.
  test/benchmarks/benchmark_compare256.cc
Labels: Testing Framework, Sanitizer issue

#1246 Rename memory alignment functions
  test/test_aligned_alloc.cc
  zutil.c
  zutil.h
Labels: cleanup

#1247 Use _msan_unposion to unposion end of window
  inflate.c
  zbuild.h
Labels: cleanup

#1233 Disable LTO in CMakeLists.txt
  CMakeLists.txt
Labels: Build Env

#1241 Fixed failed tools tests when source directory is read-only.
  CMakeLists.txt
  cmake/run-and-compare.cmake
Labels: Testing Framework

#1250 Check that sys/auxv.h exists at configure time and add preprocessor define for it.
  CMakeLists.txt
  arch/arm/arm_features.c
  arch/power/power_features.c
  arch/s390/s390_features.c
  cmake/detect-intrinsics.cmake
  configure
Labels: Build Env

#1248 Use PREFIX() for some of the Z_INTERNAL symbols
  arch/s390/crc32-vx.c
  arch/s390/dfltcc_common.c
  arch/s390/dfltcc_common.h
  arch/s390/dfltcc_deflate.c
  arch/s390/dfltcc_deflate.h
  arch/s390/dfltcc_inflate.c
  arch/s390/dfltcc_inflate.h
  arch/s390/s390_features.c
  arch/s390/s390_features.h
  cpu_features.c
  cpu_features.h
  deflate.c
  deflate.h
  deflate_p.h
  deflate_quick.c
  deflate_stored.c
  functable.c
  inflate.c
  inflate.h
  test/benchmarks/benchmark_crc32.cc
  test/test_crc32.cc
  tools/maketrees.c
  trees.c
Labels: Build Env

#1243 Remove CVE testing from configure script.
  .gitattributes
  test/Makefile.in
  test/testCVEinputs.sh
Labels: cleanup

#1256 Don't force CMAKE_BUILD_TYPE on multi config generators
  CMakeLists.txt
Labels: Build Env

#1257 Remove trailing whitespace in several source code files
  arch/arm/adler32_neon.c
  arch/arm/slide_hash_neon.c
  arch/x86/adler32_avx2.c
  arch/x86/adler32_avx512.c
  arch/x86/adler32_avx512_p.h
  arch/x86/adler32_avx512_vnni.c
  arch/x86/adler32_ssse3.c
  arch/x86/crc32_fold_pclmulqdq.c
  chunkset_tpl.h
  cmake/detect-intrinsics.cmake
Labels: cleanup

#1198 macOs M1 build fix on arm cpu checks.
  arch/arm/arm_features.c
Labels: bug

#1260 IBM Z DFLTCC: Split deflate and inflate states
  arch/s390/README.md
  arch/s390/dfltcc_common.c
  arch/s390/dfltcc_common.h
  arch/s390/dfltcc_deflate.c
  arch/s390/dfltcc_deflate.h
  arch/s390/dfltcc_detail.h
  arch/s390/dfltcc_inflate.c
  arch/s390/dfltcc_inflate.h
  deflate.c
  infback.c
  inflate.c
  inflate_p.h
Labels: cleanup, Architecture

#1259 Fixed regression introduced by inlining CRC + copy
  inflate.c
Labels: bug
