Repository zlib-ng/zlib-ng, pull requests merged in 2022-02, with the labels that each got.

#1146 More than double adler32 performance with altivec
  arch/power/adler32_vmx.c
Labels: optimization, Architecture

#1152 CI updates for codecov & wine
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1153 Obtained more ILP with VMX by breaking a data dependency
  arch/power/adler32_vmx.c
Labels: optimization, Architecture

#1154 Added power8 cpu flag to powerpc64 CMake toolchain files.
  cmake/toolchain-powerpc64.cmake
  cmake/toolchain-powerpc64le.cmake
Labels: Continuous Integration

#1156 Rename CPU feature header and source files for consistency.
  CMakeLists.txt
  arch/arm/Makefile.in
  arch/arm/arm_features.c
  arch/arm/arm_features.h
  arch/power/Makefile.in
  arch/power/power_features.c
  arch/power/power_features.h
  arch/s390/Makefile.in
  arch/s390/s390_features.c
  arch/s390/s390_features.h
  arch/x86/Makefile.in
  arch/x86/crc32_fold_pclmulqdq.c
  arch/x86/x86_features.c
  arch/x86/x86_features.h
  configure
  cpu_features.h
  fallback_builtins.h
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: cleanup

#1159 Remove unnecessary zutil.h includes.
  arch/arm/adler32_neon.c
  arch/arm/arm_features.c
  arch/arm/chunkset_neon.c
  arch/arm/crc32_acle.c
  arch/power/adler32_power8.c
  arch/power/adler32_vmx.c
  arch/power/chunkset_power8.c
  arch/power/crc32_constants.h
  arch/power/crc32_power8.c
  arch/power/power_features.c
  arch/s390/crc32-vx.c
  arch/s390/dfltcc_deflate.c
  arch/s390/s390_features.c
  arch/s390/s390_features.h
Labels: cleanup

#1160 Update NMake GitHub Actions to use Visual Studio 2022 Enterprise.
  .github/workflows/nmake.yml
Labels: Continuous Integration

#1082 Fix compilation with clang-cl on windows
  zlib-ng.h.in
  zlib.h.in
Labels: discussion, Build Env

#1171 Prevent stale stub functions from being called in deflate_slow
  deflate_slow.c
Labels: enhancement

#1164 Benchmarks compilation fix on older compilers
  test/benchmarks/CMakeLists.txt
Labels: Build Env

#1176 Fix some CI tests not running on push
  .github/workflows/fuzz.yml
  .github/workflows/libpng.yml
Labels: Build Env

#1157 Improve sse41 adler32 performance
  arch/x86/adler32_sse41.c
Labels: optimization, Architecture
