Repository zlib-ng/zlib-ng, pull requests merged in 2022-09, with the labels that each got.

#1331 Fixed content already populated error in CMake scripts.
  test/benchmarks/CMakeLists.txt
  test/pigz/CMakeLists.txt
Labels: Build Env

#1334 Actually run `configure` CI on macOS with GCC
  .github/workflows/configure.yml
Labels: Continuous Integration

#1330 Remove ZLIB_DUAL_LINK option in favor of detecting ZLIB_LIBRARIES.
  .github/workflows/link.yml
  CMakeLists.txt
  README.md
  test/CMakeLists.txt
Labels: cleanup, Continuous Integration

#1338 Fix wine32 dependencies for MinGW i686.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1345 Fix build failure introduced by 8df665005952cdbe7dc995d409ffe4f861e7a83e
  .github/workflows/link.yml
  test/CMakeLists.txt
Labels: Testing Framework

#1332 Inflate: Increase max root table sizes to 10 and 9
  infback.c
  inflate.c
  inftrees.h
Labels: enhancement

#1341 msvc/armv7: disable crc32_acle
  cmake/detect-intrinsics.cmake
Labels: Build Env, Architecture

#1344 [Compat] Don't use uint32_t for z_crc_t
  zconf.h.in
Labels: Build Env, Compatibility
