Repository zlib-ng/zlib-ng, pull requests merged in 2022-03, with the labels that each got.

#1161 Use pclmulqdq accelerated CRC for exported function
  arch/x86/crc32_fold_pclmulqdq.c
  arch/x86/crc32_fold_vpclmulqdq.c
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_crc32.cc
Labels: optimization, Architecture

#1183 Fixed inftrees.c should be compiled with infcover
  CMakeLists.txt
Labels: Build Env

#1184 Added ClangCl instances to GitHub Actions workflow.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1188 IBM Z: Delete stale self-hosted builder containers
  arch/s390/self-hosted-builder/actions-runner.service
Labels: Continuous Integration

#1141 Improve SSE2 slide hash performance
  arch/x86/slide_hash_sse2.c
Labels: optimization, Architecture, PR Dependency

#1173 Speed up chunkcopy and memset
  chunkset_tpl.h
  functable.c
  functable.h
  inffast.c
  inflate.c
  inflate_p.h
Labels: bug, optimization

#1175 Minor fixes and improvements minideflate
  test/minideflate.c
Labels: bug, enhancement

#1203 Rename adler32_sse41 to adler32_ssse3
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/adler32_sse41.c
  arch/x86/adler32_ssse3.c
  configure
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_adler32.cc
Labels: cleanup

#1205 Update language around ABI compatibility with zlib.
  PORTING.md
Labels: Compatibility

#1199 Fix an issue with the ubsan for overflow
  CMakeLists.txt
  arch/x86/adler32_avx512.c
  arch/x86/adler32_avx512_p.h
  arch/x86/adler32_avx512_vnni.c
Labels: Sanitizer issue

#1206 Fix warnings for adler32 function
  arch/x86/adler32_ssse3.c
Labels: cleanup

#1197 Add unit tests for compare256 variants.
  test/test_compare256.cc
Labels: Testing Framework

#1207 Correct typo in functable
  functable.c
Labels: bug

#1214 Fixed clang signed/unsigned warning in chunkcopy_safe.
  inflate_p.h
Labels: Warnings fix

#1185 Reinline crc
  arch/x86/crc32_fold_pclmulqdq.c
  crc32_fold.c
  crc32_fold.h
  functable.c
  functable.h
  inflate.c
  inflate.h
Labels: enhancement, optimization

#1216 Use standalone fuzzing runner only when fuzzing engine is not found.
  CMakeLists.txt
Labels: Testing Framework

#1213 Use size_t types for len arithmetic, matching signature
  arch/x86/adler32_ssse3.c
Labels: Warnings fix
