Repository zlib-ng/zlib-ng, pull requests merged in 2022-10, with the labels that each got.

#1353 Use short decompress option name for gzip compatibility.
  test/cmake/compress-and-verify.cmake
Labels: Testing Framework

#1358 Fix memcpy() overflow in adler32_fold.c and crc32_fold.c
  adler32_fold.c
  crc32_fold.c
  zbuild.h
Labels: bug

#1364 Fix deflate() with Z_BEST_COMPRESSION ignoring the dictionary
  deflate.c
Labels: bug

#1359 Fix typo in README.md
  README.md
Labels: Documentation

#1362 [MinGW] Disable GCC warning about using MS format specifiers in ISO C conformant code
  CMakeLists.txt
  configure
Labels: Build Env

#1361 Enable and fix -Wimplicit-fallthrough warnings
  CMakeLists.txt
  configure
  infback.c
  inflate.c
  zbuild.h
Labels: Warnings fix

#1354 Detect the availability of _Thread_local using a configure check
  CMakeLists.txt
  configure
  zbuild.h
Labels: Build Env
