Repository zlib-ng/zlib-ng, pull requests merged in 2022-01, with the labels that each got.

#1099 Remove old win32 readme.
  win32/README-WIN32.txt
Labels: cleanup

#1101 Fix building shared tests
  Makefile.in
  configure
Labels: Build Env

#1084 Fixed duplicate symbols in infcover when not building shared libs.
  CMakeLists.txt
Labels: Build Env

#1087 Don't build DLL sources if BUILD_SHARED_LIBS=OFF.
  CMakeLists.txt
Labels: cleanup, Build Env

#1089 Fixed crc32 assembly not returning hash value to correct variable.
  arch/x86/insert_string_sse.c
  cmake/detect-intrinsics.cmake
Labels: bug

#1065 Adler32 Avx512 optimizations
  CMakeLists.txt
  README.md
  arch/x86/Makefile.in
  arch/x86/adler32_avx512.c
  arch/x86/adler32_avx512_vnni.c
  arch/x86/x86.c
  arch/x86/x86.h
  cmake/detect-intrinsics.cmake
  configure
  functable.c
Labels: optimization, Architecture

#1093 Don't assign C versions of functions if we don't use them.
  functable.c
Labels: cleanup

#1102 Use memcpy for unaligned reads.
  chunkset.c
  compare258.c
  deflate.h
  insert_string_tpl.h
  match_tpl.h
Labels: Build Env

#1076 VPCLMULQDQ implementation of CRC32 folding
  CMakeLists.txt
  README.md
  arch/x86/INDEX.md
  arch/x86/Makefile.in
  arch/x86/crc32_fold_pclmulqdq.c
  arch/x86/crc32_fold_vpclmulqdq.c
  arch/x86/x86.c
  arch/x86/x86.h
  cmake/detect-intrinsics.cmake
  configure
Labels: optimization, Architecture

#1104 Remove unused COMPARE258 macro.
  arch/x86/compare258_avx.c
  arch/x86/compare258_sse.c
  compare258.c
  match_tpl.h
Labels: cleanup

#1095 Rename x86 source files with instruction set version.
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/adler32_avx2.c
  arch/x86/chunkset_sse2.c
  arch/x86/compare258_avx2.c
  arch/x86/compare258_sse42.c
  arch/x86/insert_string_sse42.c
  arch/x86/slide_hash_avx2.c
  arch/x86/slide_hash_sse2.c
  configure
  win32/Makefile.msc
Labels: cleanup, Architecture

#1114 Remove unmaintained and out-dated DLL FAQ.
  win32/DLL_FAQ.txt
Labels: cleanup

#1115 Remove unmaintained index markdown in arch/x86.
  arch/x86/INDEX.md
Labels: cleanup

#1107 Merge crc32_little and crc32_big
  arch/s390/crc32-vx.c
  crc32.c
  crc32_p.h
  functable.c
Labels: cleanup

#1106 Change compare258 to compare256
  CMakeLists.txt
  Makefile.in
  README.md
  arch/x86/Makefile.in
  arch/x86/compare256_avx2.c
  arch/x86/compare256_sse42.c
  compare256.c
  configure
  deflate_quick.c
  functable.c
  functable.h
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: cleanup

#1108 Improved AVX2 adler32 performance
  arch/x86/adler32_avx2.c
Labels: optimization, Architecture

#1118 Change fuzzer binaries and solutions to prefix with fuzzer_.
  CMakeLists.txt
  Makefile.in
  test/Makefile.in
  test/fuzz/fuzzer_checksum.c
  test/fuzz/fuzzer_compress.c
  test/fuzz/fuzzer_example_dict.c
  test/fuzz/fuzzer_example_flush.c
  test/fuzz/fuzzer_example_large.c
  test/fuzz/fuzzer_example_small.c
  test/fuzz/fuzzer_minigzip.c
Labels: cleanup

#1111 Adler32, compare256, crc32, slide_hash benchmarks.
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
  CMakeLists.txt
  Makefile.in
  README.md
  arch/x86/x86.c
  arch/x86/x86.h
  cpu_features.c
  cpu_features.h
  functable.c
  test/benchmarks/CMakeLists.txt
  test/benchmarks/README.md
  test/benchmarks/benchmark_adler32.cc
  test/benchmarks/benchmark_compare256.cc
  test/benchmarks/benchmark_crc32.cc
  test/benchmarks/benchmark_main.cc
  test/benchmarks/benchmark_slidehash.cc
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
Labels: enhancement

#1120 Clean up crc32_fold structure and clearly define the size.
  arch/x86/crc32_fold_pclmulqdq.c
  crc32_fold.h
  deflate.h
  inflate.h
Labels: cleanup

#1119 Clean up and remove bestcmp_t type for longest_match.
  match_tpl.h
Labels: cleanup

#1117 Merge feature list entries for crc32.
  README.md
Labels: cleanup

#1122 Fixed AVX512-VNNI detection when compiling with ClangCl.
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1130 Fixed inadvertent breakage of CPUID usage
  arch/x86/x86.c
Labels: bug

#1137 Remove unused fdopen define for MSVC.
  test/minigzip.c
  zutil.h
Labels: cleanup

#1145 Make cmake and configure release flags consistent
  configure
Labels: Build Env

#1140 Fixed GCC warning about unused variable in longest_match.
  match_tpl.h
Labels: cleanup

#1144 Intel compilers: update deprecated -wn to -Wall style
  CMakeLists.txt
Labels: Build Env

#1133 Use static keyword for vec_sumsu to prevent undefined reference error
  arch/power/adler32_power8.c
Labels: Build Env
