Repository zlib-ng/zlib-ng, pull requests merged in 2023-07, with the labels that each got.

#1530 Fix distclean target in Makefile.in
  Makefile.in
Labels: Build Env

#1534 Define an empty __msan_unpoison() without Z_MEMORY_SANITIZER
  arch/arm/chunkset_neon.c
  arch/s390/dfltcc_detail.h
  arch/x86/chunkset_avx2.c
  arch/x86/chunkset_ssse3.c
  zbuild.h
Labels: cleanup

#1537 Initial loongarch port
  cmake/detect-arch.c
  cmake/detect-arch.cmake
Labels: Architecture

#1540 Move the AVX compatibility functions into a separate file
  arch/x86/adler32_avx2_tpl.h
  arch/x86/adler32_avx512_tpl.h
  arch/x86/adler32_avx512_vnni.c
  arch/x86/crc32_pclmulqdq_tpl.h
  arch/x86/x86_intrins.h
  fallback_builtins.h
Labels: cleanup, Architecture

#1545 Configure: Fix disabling deflate_quick and deflate_medium on non-x86 arches
  configure
Labels: bug, Build Env
