Repository zlib-ng/zlib-ng, pull requests merged in 2023-05, with the labels that each got.

#1484 Include GNUInstallDirs earlier
  cmake/detect-install-dirs.cmake
Labels: Build Env

#1476 Fix Coverity warnings
  deflate_quick.c
  deflate_rle.c
Labels: Reviews wanted

#1477 Enable RISC-V cross build and test
  .github/workflows/cmake.yml
  CMakeLists.txt
  README.md
  arch/riscv/README.md
  arch/riscv/riscv_features.c
  arch/riscv/riscv_features.h
  cmake/detect-intrinsics.cmake
  cmake/toolchain-riscv.cmake
  cpu_features.c
  cpu_features.h
Labels: Architecture

#1488 Readme update
  README.md
Labels: cleanup, Continuous Integration, Build Env, Documentation

#1493 Improve configure AVX512 status message
  configure
Labels: Build Env

#1489 Add tests of file_compress/file_uncompress in minigzip and minideflate.
  test/cmake/compress-and-verify.cmake
  test/cmake/test-data.cmake
  test/cmake/test-tools.cmake
Labels: Testing Framework
