Repository zlib-ng/zlib-ng, pull requests merged in 2023-08, with the labels that each got.

#1549 Fix typo found by codespell
  arch/riscv/adler32_rvv.c
Labels: cleanup

#1502 Simplify deflate stream/state check.
  deflate.c
  deflate.h
Labels: cleanup

#1554 Remove inert check for HAVE_ACLE_FLAG in check_acle_compiler_flag.
  cmake/detect-intrinsics.cmake
Labels: cleanup

#1555 Remove march=native support from Configure.
  .github/workflows/pkgcheck.yml
  configure
Labels: cleanup

#1544 Cleanup handling of march=native
  CMakeLists.txt
Labels: cleanup, Build Env

#1556 Add CPack capability
  CMakeLists.txt
Labels: Build Env

#1561 use dash not bash for portability
  configure
Labels: Build Env
