Repository zlib-ng/zlib-ng, pull requests merged in 2023-12, with the labels that each got.

#1601 Export cmake target
  CMakeLists.txt
Labels: enhancement, Build Env

#1611 Fix pkgcheck mismatch with configure
  test/pkgcheck.sh
Labels: Build Env

#1610 Remove duplicate enable tests option
  CMakeLists.txt
Labels: Build Env

#1615 Update copyright to sync with zlib 1.3
  deflate.c
  inftrees.c
Labels: Compatibility, Documentation

#1614 Only read version information from zlib.h.in
  CMakeLists.txt
Labels: Build Env

#1612 Fix buffer overflow in compare256_rle benchmark
  test/benchmarks/benchmark_compare256_rle.cc
Labels: Testing Framework

#1397 Improve performance of crc32_acle on 32-bit ARM
  arch/arm/crc32_acle.c
Labels: optimization, information needed, Architecture

#1618 Check if compiler supports -march=native or -mcpu=native.
  CMakeLists.txt
Labels: Build Env

#1622 Always run CMake compiler feature tests without LTO.
  CMakeLists.txt
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1620 Add support for __attribute__((__target__(...))) to overcome limitations of -march=native.
  arch/arm/acle_intrins.h
  arch/arm/crc32_acle.c
  arch/arm/insert_string_acle.c
  zbuild.h
Labels: Build Env

#1619 Make sure uqsub16 mnemonic doesn't get optimized away.
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1623 Update to GoogleTest 1.12.1
  test/CMakeLists.txt
Labels: Testing Framework

#1617 Don't attempt ARMv6 detection on AARCH64.
  CMakeLists.txt
  configure
Labels: bug, Architecture

#1627 Fixed tab character in ARM ACLE uqsub16 assembly.
  arch/arm/acle_intrins.h
Labels: cleanup

#1628 Fix behavior change in inflateCopy that resulted in data corruption in our application
  inflate.c
Labels: bug

#1629 Cancel previously running CI jobs for PR or branch.
  .github/workflows/analyze.yml
  .github/workflows/cmake.yml
  .github/workflows/codeql.yml
  .github/workflows/configure.yml
  .github/workflows/fuzz.yml
  .github/workflows/libpng.yml
  .github/workflows/link.yml
  .github/workflows/nmake.yml
  .github/workflows/pigz.yml
  .github/workflows/pkgcheck.yml
Labels: Continuous Integration
