Repository zlib-ng/zlib-ng, pull requests merged in 2023-03, with the labels that each got.

#1447 IBM zSystems: Use HWCAP_S390_VXRS
  arch/s390/s390_features.c
  cmake/detect-intrinsics.cmake
Labels: Build Env, Architecture

#1454 Fix regex for visibility attribute tests
  CMakeLists.txt
Labels: Build Env

#1455 Add member to cpu_features struct if empty
  cpu_features.h
Labels: Build Env

#1458 Remove unused PREFETCH macros
  zbuild.h
Labels: cleanup
