Repository zlib-ng/zlib-ng, pull requests merged in 2023-02, with the labels that each got.

#1414 Add temporary cmake build dirs/files to gitignore
  .gitignore
Labels: cleanup, Build Env

#1405 Move initialization of functable to init_functable function
  functable.c
Labels: cleanup

#1418 Pin Google Benchmark to v1.7.1 to fix the upstream issue https://github.com/google/benchmark/issues/1454.
  test/benchmarks/CMakeLists.txt
Labels: Testing Framework

#1425 Add official Ubuntu mirror list as fallback for Actions caching proxy
  .github/workflows/analyze.yml
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
  .github/workflows/pigz.yml
  .github/workflows/pkgcheck.yml
Labels: Continuous Integration

#1426 Correct inflate_fast function signature
  cpu_features.h
  functable.c
  functable.h
Labels: Warnings fix

#1422 Use memcpy instead of memcmp for unaligned memory comparisons.
  compare256.c
  deflate_quick.c
  match_tpl.h
  zbuild.h
  zutil_p.h
Labels: cleanup, Build Env

#1432 Adjust thread counts for compiles and tests
  .github/workflows/analyze.yml
  .github/workflows/cmake.yml
  .github/workflows/libpng.yml
  .github/workflows/link.yml
  .github/workflows/pigz.yml
  .github/workflows/release.yml
  test/pkgcheck.sh
Labels: Continuous Integration

#1435 Narrow down the amount of packages installed for Wine in MinGW CI runs.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1423 Functable cleanup
  functable.c
Labels: cleanup

#1438 Use named defines instead of hard coded numbers.
  deflate.c
  deflate.h
  gzread.c.in
  infback.c
  inffast_tpl.h
  inflate.c
  inftrees.c
  test/test_deflate_hash_head_0.cc
  test/test_deflate_quick_block_open.cc
  test/test_raw.cc
  zconf-ng.h.in
  zconf.h.in
  zutil.h
Labels: cleanup

#1441 Fix warning: comparison of integer expressions of different signednes…
  test/gh1235.c
Labels: Warnings fix

#1443 Inflate: Unconditional refill and fastpath for literals
  inffast_tpl.h
  inflate_p.h
  zutil.h
Labels: optimization
