Repository zlib-ng/zlib-ng, pull requests merged in 2023-01, with the labels that each got.

#1363 Allow gtest_zlib to be manually disabled
  CMakeLists.txt
  README.md
  test/CMakeLists.txt
Labels: Testing Framework

#1401 Fix visibility of a few internal functions.
  arch/x86/crc32_fold_pclmulqdq.c
  arch/x86/crc32_fold_vpclmulqdq_tpl.h
Labels: cleanup, Compatibility

#1411 Change configure workflow to use gcc-11 for MacOS
  .github/workflows/configure.yml
Labels: Continuous Integration

#1410 Change pkgcheck to use macos-11 runner
  .github/workflows/pkgcheck.yml
Labels: Continuous Integration

#1398 Delete ctzl.h
  arch/arm/ctzl.h
Labels: cleanup

#1402 Use const char* for z_error argument
  zbuild.h
  zutil.c
Labels: cleanup

#1403 Make sure inflate_p.h is fully guarded by header guard
  inflate_p.h
Labels: cleanup

#1407 Do not use cpuid.h on Windows
  arch/x86/x86_features.c
Labels: Build Env

#1404 Fix compilation error where `crc32_fold` type matches field name in struct functable_s
  functable.h
Labels: Warnings fix

#1406 Match __builtin_ctzl/__builtin_ctzll signatures
  fallback_builtins.h
Labels: cleanup

#1384 Fix ABI checking...
  .gitattributes
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-aarch64-unknown-linux-gnu.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-arm-unknown-linux-gnueabi.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-arm-unknown-linux-gnueabihf.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-powerpc-unknown-linux-gnu.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-powerpc64-unknown-linux-gnu.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-powerpc64le-unknown-linux-gnu.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-x86_64-pc-linux-gnu-m32.abi
  test/abi/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2-x86_64-pc-linux-gnu.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-aarch64-unknown-linux-gnu.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-arm-unknown-linux-gnueabi.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-arm-unknown-linux-gnueabihf.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-powerpc-unknown-linux-gnu.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-powerpc64-unknown-linux-gnu.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-powerpc64le-unknown-linux-gnu.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-x86_64-pc-linux-gnu-m32.abi
  test/abi/zlib-ng-1ab443812aceab6c80ccd573ecdd06f73a84eef4-x86_64-pc-linux-gnu.abi
  test/abi/zlib-ng-843c16c87afd53a20bf915661012b02acdd30281-x86_64-pc-linux-gnu.abi
  test/abi/zlib-v1.2.11-arm-linux-gnueabihf.abi
  test/abi/zlib-v1.2.11-x86_64-linux-gnu.abi
  test/abicheck.sh
Labels: Continuous Integration
