Repository zlib-ng/zlib-ng, pull requests merged in 2023-04, with the labels that each got.

#1450 Shared libraries on cygwin can be named with their version number
  CMakeLists.txt
Labels: Build Env

#1459 Enable use of _mm_shuffle_epi8 on machines without SSE4.1
  CMakeLists.txt
  README.md
  arch/arm/chunkset_neon.c
  arch/generic/chunk_permute_table.h
  arch/x86/Makefile.in
  arch/x86/chunkset_avx.c
  arch/x86/chunkset_ssse3.c
  arch/x86/x86_features.c
  arch/x86/x86_features.h
  chunkset_tpl.h
  cmake/detect-intrinsics.cmake
  configure
  cpu_features.h
  functable.c
  win32/Makefile.msc
Labels: Architecture

#1463 Remove architecture dependent endian header locations
  zendian.h
Labels: Build Env

#1464 Check attribute aligned compiler support in CMake
  CMakeLists.txt
  configure
  zbuild.h
Labels: Build Env

#1460 Clean up SSE4.2 detection
  .github/workflows/cmake.yml
  CMakeLists.txt
  arch/x86/insert_string_sse42.c
  cmake/detect-intrinsics.cmake
  configure
  cpu_features.h
  functable.c
Labels: cleanup, Architecture

#1465 Fix CMake check for posix_memalign and aligned_alloc
  CMakeLists.txt
Labels: Build Env, Backport candidate

#1466 Fix compilation on OpenBSD
  zbuild.h
Labels: Build Env, Backport candidate

#1469 Ensure that unaligned compare256 variants are only used on little endian systems
  compare256.c
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_compare256.cc
  test/test_compare256.cc
Labels: Build Env, Backport candidate

#1474 Use ZLIB_INCLUDE_DIRS from FindZLIB instead of ZLIB_INCLUDE_DIR.
  test/CMakeLists.txt
Labels: Build Env

#1475 2.1.0 Beta1
  Makefile.in
  zlib-ng.h.in
  zlib.h.in
  zutil.c
Labels: Needs testing
