Repository zlib-ng/zlib-ng, pull requests merged in 2023-09, with the labels that each got.

#1562 detect intrinsics: ensure intrinsics are not optimized out before assembler is run
  cmake/detect-intrinsics.cmake
  configure
Labels: Build Env

#1538 Add ARMv6 version of slide_hash
  CMakeLists.txt
  README.md
  arch/arm/Makefile.in
  arch/arm/acle_intrins.h
  arch/arm/arm_features.c
  arch/arm/arm_features.h
  arch/arm/slide_hash_armv6.c
  cmake/detect-intrinsics.cmake
  configure
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_slidehash.cc
  win32/Makefile.arm
Labels: optimization, Architecture

#1575 Fix examining value of GENERATOR_IS_MULTI_CONFIG
  CMakeLists.txt
Labels: bug, Build Env

#1577 Match CMAKE_GENERATOR_TOOLSET variable case-insensitive
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1578 Don't run test intrinsic code with native flag in CMake.
  cmake/detect-intrinsics.cmake
Labels: cleanup, Build Env

#1579 Added instructions for cpack to readme.
  README.md
Labels: Documentation

#1581 Deprecate ZLIBNG_VER_STATUS, add new variant ZLIBNG_VER_STATUSH
  zlib-ng.h.in
  zlib.h.in
Labels: API, Compatibility

#1583 Make sure inflateCopy() allocates window with the necessary buffer padding
  inflate.c
Labels: bug
