Repository zlib-ng/zlib-ng, pull requests merged in 2023-06, with the labels that each got.

#1504 Add distclean target to arch/generic/Makefile.in
  arch/generic/Makefile.in
Labels: Build Env

#1505 Make sure file exists before adding it as dependency in configure.
  configure
Labels: Build Env

#1513 Remove COMMAND_ECHO statements only available in CMake 3.15. #1511
  test/cmake/compress-and-verify.cmake
Labels: Build Env

#1519 Try to find system copy of googletest before trying to download it.
  test/CMakeLists.txt
Labels: Build Env, Testing Framework

#1498 General Optimizations on compare256 Using RVV
  CMakeLists.txt
  README.md
  arch/riscv/compare256_rvv.c
  cpu_features.h
  functable.c
  test/benchmarks/benchmark_compare256.cc
  test/test_compare256.cc
Labels: Architecture

#1500 Minor code cleanup in deflate.c.
  deflate.c
Labels: cleanup

#1520 [PPC64] Add support for gcc > 12 and clang > 12
  .github/workflows/cmake.yml
  arch/power/chunkset_power8.c
  arch/power/compare256_power9.c
  arch/power/power_features.c
  cmake/detect-intrinsics.cmake
  cmake/toolchain-powerpc64-clang.cmake
  cmake/toolchain-powerpc64le-clang.cmake
  configure
Labels: Build Env, Architecture

#1526 Handle complete overlap in chunkcopy_safe
  inflate_p.h
Labels: bug

#1527 [ARM] Check that we have features.h before detecting float-abi
  CMakeLists.txt
Labels: Build Env, Architecture
