Repository zlib-ng/zlib-ng, pull requests merged in 2023-11, with the labels that each got.

#1593 fix cmake header path in install with custom CMAKE_INSTALL_INCLUDEDIR
  CMakeLists.txt
Labels: Build Env

#1595 pkgconfig file: propagate WITH_GZFILEOP
  CMakeLists.txt
  zlib.pc.cmakein
Labels: Build Env

#1598 [configure] Propagate -DWITH_GZFILEOP to pkgconfig
  configure
  zlib.pc.in
Labels: Build Env

#1603 Added unit test for inflate with Z_FINISH and no window.
  test/GH-1600/packobj.gz
  test/cmake/test-issues.cmake
  test/minideflate.c
Labels: Testing Framework

#1602 Fix an issue with regard to finishing out the window
  inflate.c
Labels: bug

#1591 Fix clang-cl warnings
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1597 Add adler32_fold_copy_rvv implementation.
  arch/riscv/adler32_rvv.c
  cpu_features.h
  functable.c
Labels: optimization, Architecture
