Repository zlib-ng/zlib-ng, pull requests merged in 2024-02, with the labels that each got.

#1657 Relocate CMake target export definitions
  CMakeLists.txt
Labels: Build Env

#1662 Allow overwrite NATIVEFLAG value.
  .github/workflows/cmake.yml
  CMakeLists.txt
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1676 Upgrade codecov/codecov-action to v4.
  .github/workflows/cmake.yml
  .github/workflows/pigz.yml
Labels: Continuous Integration

#1677 Update mymindstorm/setup-emsdk to v14.
  .github/workflows/cmake.yml
  .github/workflows/configure.yml
Labels: Continuous Integration

#1672 Fix PCLMULQDQ, AVX512VNNI and VPCLMULQDQ feature tests for Intel LLVM compiler (icx)
  cmake/detect-intrinsics.cmake
Labels: Build Env, Architecture

#1640 Fixed S390X CI builds not running in forked repos.
  .github/workflows/configure.yml
Labels: Continuous Integration

#1684 Rename codecov.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1687 Add dependabot for github actions
  .github/dependabot.yml
Labels: Continuous Integration

#1688 Don't export git/github-related files in tar/zip archives
  .gitattributes
Labels: cleanup

#1673 Cleanup and update NMake Makefiles.
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
  win32/depcheck.cpp
Labels: cleanup, Rebase needed, Build Env

#1683 Add test for checking if -march=native needs -mfpu=neon for 32-bit ARM.
  cmake/detect-intrinsics.cmake
Labels: Build Env
