Repository zlib-ng/zlib-ng, pull requests merged in 2024-04, with the labels that each got.

#1698 Fix building with NVHPC
  arch/x86/x86_intrins.h
Labels: Build Env

#1701 Allow disabling runtime CPU features detection in tests and benchmarks
  CMakeLists.txt
  Makefile.in
  cpu_features.h
  test/benchmarks/benchmark_adler32.cc
  test/benchmarks/benchmark_adler32_copy.cc
  test/benchmarks/benchmark_compare256.cc
  test/benchmarks/benchmark_crc32.cc
  test/benchmarks/benchmark_main.cc
  test/benchmarks/benchmark_slidehash.cc
  test/test_adler32.cc
  test/test_compare256.cc
  test/test_cpu_features.h
  test/test_crc32.cc
  test/test_main.cc
Labels: Build Env

#1703 Remove obsolete TARGET_OS_MAC check
  zutil.h
Labels: Build Env, Compatibility

#1704 Optimized rvv slide_hash
  arch/riscv/slide_hash_rvv.c
Labels: optimization, Architecture

#1707 CMake: Replace `;` by `$<SEMICOLON>` in generator-expression
  CMakeLists.txt
Labels: Build Env

#1711 Update dependencies for 32-bit MinGW CI run.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1700 arch/riscv/riscv_features.c: fix uclibc build
  arch/riscv/riscv_features.c
Labels: Build Env, Architecture
