Repository zlib-ng/zlib-ng, pull requests merged in 2024-12, with the labels that each got.

#1814 Fix casting warning/error in test_compress_bound.cc
  test/test_compress_bound.cc
Labels: Warnings fix

#1818 Fix native detection of ARM CRC instruction
  arch/arm/arm_functions.h
Labels: Build Env, Architecture

#1812 Address deprecated cmake version warning.
  CMakeLists.txt
  test/add-subdirectory-project/CMakeLists.txt
  test/fuzz/CMakeLists.txt
Labels: Build Env

#1816 Enable AVX2 functions to be built with BMI2 instructions
  arch/x86/Makefile.in
  cmake/detect-intrinsics.cmake
  configure
  functable.c
Labels: optimization, Architecture

#1820 Add a fallback to ALIGNED_ macro for other compilers
  zbuild.h
Labels: Build Env

#1821 Improve pipeling for AVX512 chunking
  arch/x86/chunkset_avx512.c
  chunkset_tpl.h
Labels: optimization, Architecture

#1828 Remove UNALIGNED_OK checks
  .github/workflows/cmake.yml
  CMakeLists.txt
  README.md
  arch/generic/compare256_c.c
  arch/generic/generic_functions.h
  chunkset_tpl.h
  cmake/detect-sanitizer.cmake
  compare256_rle.h
  configure
  deflate_rle.c
  insert_string_tpl.h
  match_tpl.h
  test/benchmarks/benchmark_compare256.cc
  test/benchmarks/benchmark_compare256_rle.cc
  test/test_compare256.cc
  test/test_compare256_rle.cc
  zbuild.h
Labels: cleanup

#1826 adler32_rvv: Fix two overflow problems
  arch/riscv/adler32_rvv.c
Labels: bug, Architecture

#1831 Make big endians first class citizens again
  arch/generic/compare256_c.c
  arch/generic/generic_functions.h
  zbuild.h
Labels: optimization, Architecture

#1834 Set OPTIMAL_CMP for 32-bit PowerPC
  cmake/detect-arch.c
  zbuild.h
Labels: Build Env, Architecture

#1782 Update s390x actions-runner docker
  arch/s390/README.md
  arch/s390/self-hosted-builder/actions-runner
  arch/s390/self-hosted-builder/actions-runner-rebuild.sh
  arch/s390/self-hosted-builder/actions-runner.Dockerfile
  arch/s390/self-hosted-builder/actions-runner.service
  arch/s390/self-hosted-builder/entrypoint
  arch/s390/self-hosted-builder/fs/usr/bin/actions-runner
  arch/s390/self-hosted-builder/runner-global.json
  arch/s390/self-hosted-builder/runner-s390x.patch
Labels: Continuous Integration, Documentation

#1833 Fix unaligned access in ACLE based crc32
  arch/arm/crc32_acle.c
  test/test_crc32.cc
Labels: bug, Architecture

#1548 Use GCC's may_alias attribute for unaligned memory access
  arch/arm/chunkset_neon.c
  arch/arm/compare256_neon.c
  arch/generic/Makefile.in
  arch/generic/chunkset_c.c
  arch/generic/compare256_c.c
  arch/power/chunkset_power8.c
  arch/power/compare256_power9.c
  arch/riscv/compare256_rvv.c
  arch/x86/chunkset_avx2.c
  arch/x86/chunkset_avx512.c
  arch/x86/chunkset_sse2.c
  arch/x86/chunkset_ssse3.c
  arch/x86/compare256_avx2.c
  arch/x86/compare256_sse2.c
  compare256_rle.h
  deflate.h
  deflate_quick.c
  inflate_p.h
  insert_string_tpl.h
  match_tpl.h
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
  zmemory.h
  zutil_p.h
Labels: optimization, Build Env

#1830 Continued cleanup of old UNALIGNED_OK checks
  CMakeLists.txt
  arch/generic/Makefile.in
  arch/generic/compare256_c.c
  arch/generic/compare256_p.h
  arch/generic/generic_functions.h
  compare256_rle.h
  deflate_rle.c
  functable.c
  match_tpl.h
  test/benchmarks/benchmark_compare256.cc
  test/benchmarks/benchmark_compare256_rle.cc
  test/test_compare256.cc
  test/test_compare256_rle.cc
  zbuild.h
  zmemory.h
Labels: cleanup, Benchmarks wanted
