Repository zlib-ng/zlib-ng, pull requests merged in 2024-01, with the labels that each got.

#1632 Remove tab-in-indent rule from lint workflow
  .github/workflows/lint.yml
Labels: Continuous Integration

#1634 Added CI instance for WITH_NATIVE_INSTRUCTIONS.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1637 Add FAR macro to zlib-compat headers to improve compatibility.
  zconf.h.in
Labels: Compatibility

#1633 Remove unneeded pointer for functable.longest_match in deflate_slow
  deflate_slow.c
Labels: cleanup

#1655 Removing some outdated comments
  inflate.c
Labels: cleanup

#1649 Fix regression caused by 2fa631e029084b75acd81db5d33fd4aa802fd082
  CMakeLists.txt
  arch/power/power_features.c
  cmake/detect-intrinsics.cmake
Labels: Build Env

#1647 Generate CMake package configuration files
  CMakeLists.txt
  zlib-config.cmake.in
  zlib-ng-config.cmake.in
Labels: Build Env
