Repository zlib-ng/zlib-ng, pull requests merged in 2024-03, with the labels that each got.

#1675 [CI] Fix creating list of artifacts for CodeCov.
  .github/workflows/cmake.yml
  .github/workflows/pigz.yml
Labels: Continuous Integration

#1696 Rename cpu_functions.h to arch_functions.h in depcheck.cpp
  win32/depcheck.cpp
Labels: cleanup

#1694 [ARM] Override Clang x4 NEON intrinsics for Android
  arch/arm/neon_intrins.h
Labels: Architecture
