Repository zlib-ng/zlib-ng, pull requests merged in 2024-05, with the labels that each got.

#1714 make darwin cross compilation possible
  configure
Labels: Build Env

#1715 .gitattributes: Enforce LF line-endings on all non-binary files
  .gitattributes
Labels: cleanup

#1721 Add small compress() benchmark
  test/benchmarks/CMakeLists.txt
  test/benchmarks/benchmark_compress.cc
Labels: Testing Framework

#1725 Use windows-2019 for build with toolset v141
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1723 Fix invalid instruction usage in Xeon Phi x200 processors
  arch/x86/x86_features.c
  arch/x86/x86_features.h
  functable.c
  test/benchmarks/benchmark_adler32.cc
  test/benchmarks/benchmark_adler32_copy.cc
  test/benchmarks/benchmark_crc32.cc
  test/test_adler32.cc
  test/test_crc32.cc
Labels: Architecture

#1730 Fix a name conflict when compiled with zlib-compat
  test/benchmarks/benchmark_compress.cc
Labels: Testing Framework

#1726 Fix MSAN error in test_dict
  test/test_dict.cc
Labels: Testing Framework, Sanitizer issue

#1731 Add back-and-forth inflateCopy() test
  test/CMakeLists.txt
  test/test_inflate_copy.cc
Labels: Testing Framework

#1729 Codecov fixes
  .github/workflows/cmake.yml
  .github/workflows/pigz.yml
Labels: Continuous Integration

#1734 Simplify inflate window checks
  arch/s390/dfltcc_inflate.c
  inflate.c
  inflate.h
Labels: cleanup
