Repository zlib-ng/zlib-ng, pull requests merged in 2024-06, with the labels that each got.

#1710 free_aligned: validate passed in pointer
  zutil.c
Labels: Compatibility

#1727 Improved ACLE check
  cmake/detect-intrinsics.cmake
  configure
Labels: Build Env, Architecture

#1750 don't use zlib-ng's -Wl,--version-script in tests
  Makefile.in
  configure
Labels: Backport candidate
