Repository zlib-ng/zlib-ng, pull requests merged in 2024-09, with the labels that each got.

#1771 Fix new Windows SDK build break
  functable.c
Labels: Build Env

#1773 Don't use chunkunroll for inflateBack
  inffast_tpl.h
Labels: bug, Backport candidate

#1770 [RISCV] Better run-time detection of RVV vector instruction support
  arch/riscv/riscv_features.c
Labels: Architecture

#1776 Split chunkcopy_safe to allow the first part to be inlined more often.
  inflate.c
  inflate.h
  inflate_p.h
Labels: optimization

#1695 Make use of unaligned loads on big endian in insert_string
  insert_string_tpl.h
Labels: Architecture

#1783 Fix build on aarch64 android.
  CMakeLists.txt
Labels: Build Env, Backport candidate

#1784 Use target include instead of raw include
  CMakeLists.txt
Labels: Build Env, Backport candidate

#1790 [CI] Don't try to use macOS 11 as it's no longer supported.
  .github/workflows/pkgcheck.yml
  test/pkgcheck.sh
Labels: Continuous Integration

#1781 Allow the compiler to inline chunkcopy_safe more readily
  inflate_p.h
Labels: optimization

#1792 Explicitly set CMake policy 0169 to silence warning
  CMakeLists.txt
  test/CMakeLists.txt
Labels: Build Env
