Repository zlib-ng/zlib-ng, pull requests merged in 2025-08, with the labels that each got.

#1949 Unroll some of the adler checksum for avx2
  arch/x86/adler32_avx2.c
Labels: optimization, Architecture

#1954 Optimize compress_block() and build_tree()
  trees.c
Labels: optimization

#1956 Add benchmark for insert_string.
  test/benchmarks/CMakeLists.txt
  test/benchmarks/benchmark_insert_string.cc
Labels: Testing Framework
