Repository zlib-ng/zlib-ng, pull requests merged in 2025-03, with the labels that each got.

#1880 Fix incorrect declaration of FORCE_SSE2
  CMakeLists.txt
Labels: Build Env

#1882 fix the url of the s390x actions worker patch
  arch/s390/self-hosted-builder/actions-runner.Dockerfile
Labels: Continuous Integration

#1863 port: Use memalign or _aligned_malloc only, when available, fallback to malloc.
  CMakeLists.txt
  configure
  zutil_p.h
Labels: Build Env

#1886 Minor fix for s390x CI runner
  arch/s390/self-hosted-builder/actions-runner.Dockerfile
Labels: Continuous Integration

#1884 Disable MSVC optimizations for AVX512 GET_CHUNK_MAG
  arch/x86/chunkset_avx512.c
Labels: bug, Build Env, Architecture

#1889 riscv: chunkset_rvv: fix SIGSEGV in CHUNKCOPY
  arch/riscv/chunkset_rvv.c
Labels: Architecture

#1872 Explicit SSE2 vectorization of Chorba CRC method
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/chorba_sse2.c
  arch/x86/x86_functions.h
  arch/x86/x86_intrins.h
  configure
  crc32.h
  functable.c
  test/benchmarks/benchmark_crc32.cc
  test/test_crc32.cc
  win32/Makefile.msc
Labels: optimization, Architecture
