Repository zlib-ng/zlib-ng, pull requests merged in 2025-01, with the labels that each got.

#1839 Force use of latest Windows SDK with 32-bit ARM support for release workflows
  .github/workflows/release.yml
Labels: Continuous Integration

#1850 cmake: disable LTO for some configure checks
  CMakeLists.txt
Labels: Build Env

#1846 s390x docker rebuild script improvements
  arch/s390/self-hosted-builder/actions-runner-rebuild.sh
  arch/s390/self-hosted-builder/actions-runner.Dockerfile
Labels: Continuous Integration

#1852 Disable CRC32-VX Extention for some Clang versions
  arch/s390/s390_functions.h
Labels: Build Env, Architecture

#1857 [abicheck] Regenerate ABI files for zlib
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-aarch64-unknown-linux-gnu.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-arm-unknown-linux-gnueabi.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-arm-unknown-linux-gnueabihf.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-mips-unknown-linux-gnu.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-mips64-unknown-linux-gnuabi64.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-powerpc-unknown-linux-gnu.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-powerpc64-unknown-linux-gnu.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-powerpc64le-unknown-linux-gnu.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-x86_64-pc-linux-gnu-m32.abi
  test/abi/zlib-04f42ceca40f73e2978b50e93806c2a18c1281fc-x86_64-pc-linux-gnu.abi
Labels: Continuous Integration

#1858 s390x: Update CI clang version
  arch/s390/self-hosted-builder/actions-runner
  arch/s390/self-hosted-builder/actions-runner-rebuild.sh
  arch/s390/self-hosted-builder/actions-runner.Dockerfile
Labels: Continuous Integration
