Repository zlib-ng/zlib-ng, pull requests merged in 2025-05, with the labels that each got.

#1904 riscv: add bash configure script support for riscv
  .github/workflows/configure.yml
  .github/workflows/pkgcheck.yml
  arch/riscv/Makefile.in
  configure
Labels: Build Env

#1913 Add large 1mb buffer test for crc32 hashing.
  test/test_crc32.cc
Labels: Testing Framework

#1915 [WebAssembly] Fix stack overflow in crc32_chorba_118960_nondestructive.
  arch/generic/crc32_chorba_c.c
Labels: Build Env

#1912 Fix 32bit large chorba
  arch/generic/crc32_chorba_c.c
Labels: bug
