Repository zlib-ng/zlib-ng, pull requests merged in 2025-04, with the labels that each got.

#1894 CI: Preinstall packages needed for testing and benchmark.
  .github/workflows/cmake.yml
Labels: Continuous Integration

#1900 [FreeBSD] Define _XOPEN_SOURCE for gtest_zlib
  test/CMakeLists.txt
Labels: Build Env

#1899 Remove NMake build projects
  .github/workflows/nmake.yml
  README.md
  win32/Makefile.a64
  win32/Makefile.arm
  win32/Makefile.msc
  win32/depcheck.cpp
  win32/replace.vbs
Labels: Build Env

#1892 CI: Changes to running benchmark
  .github/workflows/cmake.yml
  test/benchmarks/CMakeLists.txt
  test/benchmarks/benchmark_slidehash.cc
Labels: Continuous Integration, Testing Framework

#1901 Add AVX512 version of compare256
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/compare256_avx512.c
  arch/x86/x86_functions.h
  configure
  functable.c
  test/benchmarks/benchmark_compare256.cc
  test/test_compare256.cc
Labels: optimization, Architecture

#1887 port: Use __cpuid only, when available.
  CMakeLists.txt
  arch/x86/x86_features.c
  configure
Labels: Build Env

#1893 SSE4.1 optimized chorba
  CMakeLists.txt
  arch/x86/Makefile.in
  arch/x86/chorba_sse41.c
  arch/x86/x86_features.c
  arch/x86/x86_features.h
  arch/x86/x86_functions.h
  cmake/detect-intrinsics.cmake
  configure
  functable.c
  test/benchmarks/benchmark_crc32.cc
  test/test_crc32.cc
Labels: optimization, Rebase needed, Architecture

#1905 riscv: add crc32 optimization using zbc extension
  CMakeLists.txt
  arch/riscv/crc32_zbc.c
  arch/riscv/riscv_features.c
  arch/riscv/riscv_features.h
  arch/riscv/riscv_functions.h
  cmake/detect-intrinsics.cmake
  functable.c
  test/benchmarks/benchmark_crc32.cc
  test/test_crc32.cc
Labels: optimization, Architecture
